
server:
  port: 8070

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-routes
          uri: http://auth-service:8071
          predicates:
            - Path=/api/auth/**
      
